### ISSUE TITLE
bnuy task list cause brain empty rn 💀 

### ISSUE THREAD

**Issue by ppaawwll** [DFHack/dfhack#2804]
- [ ] look into spawning food items
- [ ] look into writing a script that spawns the bodies of dead units that had their bodies destroyed (or lost)
- [ ] add the ability to spawn whole unbutchered body parts into gui/create-item
- [ ] start looking into trying to make a gui for editing the map and painting blocks
