### ISSUE TITLE
Easily fixable UI bugs

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#526]
- [x] [#614](http://www.bay12games.com/dwarves/mantisbt/view.php?id=614): HOTKEY_KITCHEN_\* bindings are unused/ignored
- [x] [#1518](http://www.bay12games.com/dwarves/mantisbt/view.php?id=1518): When naming burrows, "ESC: Back" appears on screen, but Esc does nothing
- [x] [#2091](http://www.bay12games.com/dwarves/mantisbt/view.php?id=2091): Cursor moves in addition to reserved barrel increase from [p] stockpile screen
~~- [ ] [#2523](http://www.bay12games.com/dwarves/mantisbt/view.php?id=2523): LEAVESCREEN when designating "Set Traffic" and "Set Item/Building properties" works like LEAVESCREEN_ALL~~
- [x] [#6277](http://www.bay12games.com/dwarves/mantisbt/view.php?id=6277): Frame rate cap can't be increased after decreasing it below 10 FPS (using in-game keystrokes)
- [x] [#7879](http://www.bay12games.com/dwarves/mantisbt/view.php?id=7879): Can't use \* (asterisk) to page selection down in contexts where view/cursor can be moved
~~- [ ] [#8079](http://www.bay12games.com/dwarves/mantisbt/view.php?id=8079): "1 point remain" in embark confirmation~~
- [x] [#9000](http://www.bay12games.com/dwarves/mantisbt/view.php?id=9000): "You have no appropriate ingredients" warning covers some kitchen tab titles
