### ISSUE TITLE
Plugin system-related issues

### ISSUE THREAD

**Issue by lethosor** [DFHack/dfhack#666]
- [x] `plug` only lists plugins with commands
- [x] The name passed to `DFHACK_PLUGIN` does not have to match the plugin filename (RemoteFortressReader vs. remotefortressreader, for example), allowing for possible name collisions
- [x] Plugins that don't exist on startup can't be loaded later
- [x] Plugins that are deleted after startup produce an unhelpful error message when reloaded (different from the message for other nonexistent plugins)
- [x] `ls` gives no feedback for unloaded plugins
- [x] `load`/`unload`/`reload` give no feedback for broken plugins
